name: Samples - Regular Checks
on:
  pull_request:
    branches:
      - main
    paths:
      - "samples/**"
jobs:
  # outputs matrix json so that windows is only added when head branch is a release branch
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ env.MATRIX }}
    env:
      MATRIX: '{ "os": [ "ubuntu-latest" ] }'
      COLON: ':'
    steps:
      - name: Windows
        id: windows
        if: startsWith(github.head_ref, 'release/') == true
        run: echo "MATRIX={ \"os\"$COLON [ \"ubuntu-latest\", \"windows-latest\" ] }" >> $GITHUB_ENV
  build-and-test:
    name: Build & Test
    needs: Prepare
    strategy:
      max-parallel: 2
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
      - name: empty
        working-directory: empty
        run: |
          echo "build & test empty"
      - name: tutorial/hello-world
        working-directory: tutorial/hello-world
        run: |
          echo "build & test tutorial/hello-world"
      - name: tutorial/persistent-classes
        working-directory: tutorial/persistent-classes
        run: |
          echo "build & test tutorial/persistent-classes"
      - name: tutorial/database-transactions
        working-directory: tutorial/database-transactions
        run: |
          echo "build & test tutorial/database-transactions"
      - name: tutorial/query-classes
        working-directory: tutorial/query-classes
        run: |
          echo "build & test tutorial/query-classes"
      - name: tutorial/rest-api
        working-directory: tutorial/rest-api
        run: |
          echo "build & test tutorial/rest-api"
      - name: todo
        working-directory: to-do
        run: |
          echo "build & test to-do"
